# Generated by Django 4.2.6 on 2023-11-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_person_tg_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='tg_code',
        ),
    ]
