# Generated by Django 4.2.6 on 2023-11-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_remove_person_tg_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tg_code',
            field=models.PositiveIntegerField(blank=True, help_text='Telegram code to understand who you are', null=True, unique=True),
        ),
    ]
