# Generated by Django 4.2.6 on 2023-11-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_person_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tg_id',
            field=models.CharField(blank=True, help_text='Write here your Telegram ID', max_length=150, null=True, unique=True),
        ),
    ]
