# Generated by Django 4.2.6 on 2023-10-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Write here name of the dish', max_length=150)),
                ('description', models.TextField(help_text='Write here description of the dish')),
                ('photo', models.ImageField(upload_to='dishes/')),
                ('price', models.PositiveIntegerField(default=0, help_text='Write here price of dish in som')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Write here name of the restaurant', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Write here description of the restaurant', null=True)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('average_bill', models.IntegerField(default=0, help_text='Write here average bill of restaurant in som')),
                ('tables', models.PositiveIntegerField(default=0, help_text='Write here amount of tables that can be reserved')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('dishes', models.ManyToManyField(to='restaurant.dish')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.person')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Write here type of cuisine', max_length=150)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('reserved_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_auth.person')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('positive_or_not', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', max_length=100)),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='user_auth.person')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.ManyToManyField(to='restaurant.type'),
        ),
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.type'),
        ),
    ]
