# Generated by Django 4.2.6 on 2023-10-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_table_reserved_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='dishes',
            field=models.ManyToManyField(to='restaurant.dish'),
        ),
    ]
