# Generated by Django 4.2.6 on 2023-10-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_dish_made_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='description',
        ),
    ]
