# Generated by Django 4.2.6 on 2023-10-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='drinks',
            field=models.ManyToManyField(to='restaurant.drink'),
        ),
    ]
