# Generated by Django 4.2.6 on 2023-10-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_restaurant_drinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='amount',
            field=models.CharField(blank=True, help_text='Write here amount of product', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='amount',
            field=models.CharField(blank=True, help_text='Write here amount of product', max_length=150, null=True),
        ),
    ]
