# Generated by Django 4.2.6 on 2023-10-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_category_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to='plans/'),
        ),
    ]
