# Generated by Django 4.2.6 on 2023-10-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='dishes',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.dish'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='drinks',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.drink'),
        ),
    ]
