# Generated by Django 4.2.6 on 2023-10-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_alter_cart_dishes_alter_cart_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='dishes',
            field=models.ManyToManyField(to='restaurant.dish'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='drinks',
            field=models.ManyToManyField(to='restaurant.drink'),
        ),
    ]
