# Generated by Django 4.2.6 on 2023-11-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_table_d_table_drinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='viewbox',
            field=models.CharField(blank=True, help_text='Need for plan', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='d',
            field=models.CharField(blank=True, help_text='Need for plan', max_length=250, null=True),
        ),
    ]
