# Generated by Django 4.2.6 on 2024-12-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_cart_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/'),
        ),
    ]
