# Generated by Django 4.2.6 on 2024-12-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_cart_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='restaurant.dish'),
        ),
        migrations.AlterField(
            model_name='table',
            name='drinks',
            field=models.ManyToManyField(blank=True, to='restaurant.drink'),
        ),
    ]
