# Generated by Django 4.2.6 on 2025-01-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_remove_cart_dishes_remove_cart_drinks_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='drink',
        ),
    ]
