# Generated by Django 4.2.6 on 2025-01-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_person_tg_id'),
        ('restaurant', '0024_cartitem_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='table',
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='table',
            name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='table',
            name='reserved_by',
        ),
        migrations.RemoveField(
            model_name='table',
            name='reserved_time',
        ),
        migrations.AddField(
            model_name='table',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TableDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.dish')),
                ('drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.drink')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.table')),
            ],
            options={
                'verbose_name': 'Table dish',
                'verbose_name_plural': 'Table dishes',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Start time for reservation')),
                ('end_time', models.DateTimeField(help_text='End time for reservation')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_auth.person')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.table')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
