# Generated by Django 4.2.6 on 2025-01-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_remove_table_dishes_remove_table_drinks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledish',
            name='table',
        ),
        migrations.AddField(
            model_name='tabledish',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.reservation'),
        ),
    ]
