# Generated by Django 4.2.6 on 2025-01-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_remove_tabledish_table_tabledish_reservation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('table', 'start_time', 'end_time')},
        ),
    ]
